### ISSUE TITLE
feature: template engine

### ISSUE THREAD

**Issue by icyleaf** [icyleaf/wasp#4]
However, [liquid.cr](https://github.com/TechMagister/liquid.cr) is wasp’s template engine but it's not completed, and not enough in many issues. i forked it. let's see what will happen.

todo:

- [x] wasp variables
- [x] site variables
- [x] page variables

**Comment by straight-shoota** [comment]
You could take a look at [straight-shoota/crinja](https://github.com/straight-shoota/crinja) which implements the Jinja2 template engine in Crystal. The syntax is very similar to liquid (both are inspired by Django's template language), but Jinja is much more powerful, as it supports for example template inheritance and macros, which might be very valuable for a static site generator.

**Comment by icyleaf** [comment]
Thanks, i will check it out.

**Comment by icyleaf** [comment]
Finally, wasp was switch to crinja :)
